#!/usr/bin/env bash
# Installs and setup haproxy

apt-get -y install software-properties-common
add-apt-repository ppa:vbernat/haproxy-1.8
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
printf %s "listen 97299-webs
    bind *:80
    mode http
    balance roundrobin
    server 97299-web-01 54.174.230.101:80 check
    server 97299-web-02 100.26.57.164:80 check
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
