#!/bin/bash
find /root/alx-system_engineering-devops/0x00-shell_basics -maxdepth 1 -type f -name "*.html" -newer /root/alx-system_engineering-devops -exec cp -n {} /root/alx-system_engineering-devops \;
